### PR TITLE
Support for Swift 5.6

### PR DESCRIPTION
**Pull request by daveverwer**
Hi Jhonatan!

I’d love to add both of these packages (SwiftSafeURL and 
XcodeIssueReporting) to the [Swift Package Index](https://swiftpackageindex.com). Unfortunately we currently don’t support Swift 5.7 packages as it’s still in beta. However, I checked by building them locally with 5.6 and I don’t think you’re using any 5.7 specific features?

Would you consider these PRs to reduce the tools version?

Thanks!

### CODE REVIEW

**Comment by jhonatn** [comment]
Hi Dave! I can drop that requirement. In fact, this library doesn't need a lot of features and Xcode seems to be happy with it, so I dropped the Swift version to 5.0 over at 81e902f09fb9081240bb446a4d4549cce76b9362. Hope that helps!

**Comment by daveverwer** [comment]
That's great, thanks so much Jhonatan!

**Comment by daveverwer** [comment]
Actually, I just checked our compatibility results and it looks like you are using *something* that requires 5.6 as all builds with 5.5 and below are failing:

https://swiftpackageindex.com/baguio/XcodeIssueReporting/builds

I think 5.6 might be the best choice to inform your users of compatibility

**Comment by jhonatn** [comment]
I think there were some problems with the Package.resolved file I included in the project before, so I updated it to one with a lower version and now the build results at SPI look a lot better

**Pull request closed without merging**
